### ISSUE TITLE
NullReferenceException in Science Archives (Kopernicus.RuntimeUtility.RnDFixer.LateUpdate)

### ISSUE THREAD

**Issue by lampeh** [prestja/Kopernicus#1]
I'm not sure which issue tracker to use, so I'll drop it here :)

A NullReferenceException loop happens when entering the Science Archives in RnD multiple times:
```
NullReferenceException
  Kopernicus.RuntimeUtility.RnDFixer.LateUpdate () (at <2e7f9d27a35d4685baca4f1cd2ad3a82>:0)
  UnityEngine.DebugLogHandler:LogException(Exception, Object)
  ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
  UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
The exception does not occur when entering the archives for the first time after loading KSP. The planetary system is just stock (+ Kopernicus).

Video: https://imgur.com/5lpvDB5
[KSP.log](https://github.com/prestja/Kopernicus/files/4816189/KSP.log)
[persistent.sfs.txt](https://github.com/prestja/Kopernicus/files/4816190/persistent.sfs.txt)

After adding some debug logging, the exception happens [here](https://github.com/prestja/Kopernicus/blob/master/src/Kopernicus/RuntimeUtility/RnDFixer.cs#L51) because ``RnDRotationKill[i]`` is null for all but the last element. I don't really know enough about the code yet to say why that happens or how to fix it.

It looks like every time the science archive appears, a RDPlanetListItemContainer for the sun (with the stock planets) is [added](https://github.com/prestja/Kopernicus/blob/master/src/Kopernicus/RuntimeUtility/RnDFixer.cs#L325) to the list. After leaving the archives, the referenced element is deleted/set to null by KSP(?). Maybe the component should be destroyed or reset on leaving the R&D?

A workaround that works for me is to remove "null" elements in LateUpdate:

```
diff --git a/src/Kopernicus/RuntimeUtility/RnDFixer.cs b/src/Kopernicus/RuntimeUtility/RnDFixer.cs
index bc4922a..f99272b 100755
--- a/src/Kopernicus/RuntimeUtility/RnDFixer.cs
+++ b/src/Kopernicus/RuntimeUtility/RnDFixer.cs
@@ -45,9 +45,16 @@ namespace Kopernicus.RuntimeUtility
         private void LateUpdate()
         {
             // Kill the rotation of selected planet thumbnails
-            for (Int32 i = 0; i < RnDRotationKill.Count; i++)
+            for (Int32 i = RnDRotationKill.Count; i > 0; i--)
             {
-                RDPlanetListItemContainer planetItem = RnDRotationKill[i];
+                RDPlanetListItemContainer planetItem = RnDRotationKill[i-1];
+
+                if (planetItem == null)
+                {
+                    RnDRotationKill.RemoveAt(i-1);
+                    continue;
+                }
+
                 planetItem.planet.transform.rotation = Quaternion.identity;
             }
         }
```

**Comment by R-T-B** [comment]
As this doesn't actually crash the game or aparently hurt anything really, we don't consider it a blocker to CKAN release.  Still, leaving this open and letting you know I will be testing your patch on my bleeding edge branch for it's potential side effects.  If there are none, I see no harm in less null references, heh.

Thanks for this.

**Comment by democat3457** [comment]
I don't think this code will work. The `RnDRotationKill` list is only added to on `Start()`, meaning that once elements are removed, they aren't added back. If the line that removes the elements is removed, it should work fine because it skips over the part that causes it to be `null` without changing anything. This would also suggest that changing the for loop structure is not needed, because a simple null check should suffice.

**Comment by R-T-B** [comment]
Yeah, I've got to be completely honest I only glanced over this because Issue #16 was grabbing my attention.

I'll review this in more detail tomorrow though.

**Comment by lampeh** [comment]
> I don't think this code will work.

It does work. I tested it :)

> The `RnDRotationKill` list is only added to on `Start()`, meaning that once elements are removed, they aren't added back.

That's not what I see happening.

Upon first entering the science archives in a stock system, the list is empty and "[sun]" is appended.
Leaving and entering RnD once, the list is now "[null]" with the code extending it to "[null, sun]".
Leave and enter once more, the list becomes "[null, null, sun]" and so on.

I concur that iterating over null elements won't hurt performance much unless a player enters the archives a few hundred times per session, so a simple null check without reversing the loop or modifying the list would suffice.

I *think* the underlying bug is that the RnDRotationKill list probably should not survive exiting the RnD archives. I haven't found the right place to destroy the RnDFixer component, though.

**Comment by democat3457** [comment]
Ah. `Start()` could be called upon entering the Rnd archives, which would make it work.

**Comment by R-T-B** [comment]
Yeah, I tested it in my branch and it does indeed work.  Pushing to a release there to measure side effects.

**Comment by R-T-B** [comment]
Side effects seem minimal/non-existant.  This would probably be a good patch for next release, if Prestja sees fit.

Thanks for the advice/contribution, @lampeh

**Comment by R-T-B** [comment]
This has been added to the tree for the next stable build.  Will close when it is generally available.

**Comment by R-T-B** [comment]
This has been integrated a while ago with no issues, forgot to close, doing so now.
