### ISSUE TITLE
Oceans Are Invisible 

### ISSUE THREAD

**Issue by Its-Just-Luci** [prestja/Kopernicus#15]
No Oceans in rss 1.9.1

**Comment by R-T-B** [comment]
We had a fix for this (or a similar issue anyways) a few releases ago...  can I get a KSP.log from you to confirm you are on the right release and/or further diagnose?

You should be able to find the "KSP.log" file in your KSP install directory.  In steam, right clicking the program and selecting "Properties" then "Local FIles" tab and clicking "Browse Local Files" will get you there.

On some systems, the file may be missing the ".log" part, but if there is a text file named "KSP" in there that's the one.  Upload somewhere and link please, thank you.

**Comment by R-T-B** [comment]
Closing as I assume you must be on an old version, update if not please.
