### ISSUE TITLE
Non-Jool Template using gas giants have shading issues

### ISSUE THREAD

**Issue by VabienArt** [prestja/Kopernicus#16]
Gas Giants not using the jool template, such as the Kopernicus Template gas giant, have shadows rotated 90 degrees

Previous Thread on 1.10 Build: https://github.com/R-T-B/Kopernicus/issues/13

![Kerbal Space Program 7_16_2020 9_50_34 PM](https://user-images.githubusercontent.com/24655216/87740692-d29e9080-c7b0-11ea-98d2-9e3f4440a4ad.png)

**Comment by R-T-B** [comment]
Confirmed on my 1.10 branch, I assume it's an old issue as he says, possibly even 1.8-old.  I'd advise one more release to fix this and then say we're CKAN ready.
I'm attempting a fix on my branch and will make a PR if it works.

**Comment by R-T-B** [comment]
This is confirmed to date back to 1.8.  I have a fix, but I need to isolate it from my 1.10 branch code.  It may take a moment to do so, but I will have a pull request soon.

**Comment by R-T-B** [comment]
This might be fixed in this PR, but wait for testing on my branch before merging:

https://github.com/prestja/Kopernicus/pull/17

**Comment by R-T-B** [comment]
Don't merge that, there are much better ways to handle this and it doesn't work anyways.  Closing that pull request.

**Comment by VabienArt** [comment]
Fixed on 1.10. Won't close until that change gets merged to this version.

**Comment by R-T-B** [comment]
Heh, I already merged the fix over here.  Felt it important enough to get it out.

Hope no one objects.  It's in release 5 for 1.9.1.
