### ISSUE TITLE
Why it require Ultra shader

### ISSUE THREAD

**Issue by dogevspenguin** [prestja/Kopernicus#21]
It is laggy on my 11 year old computer

**Comment by democat3457** [comment]
Because KSP has an Ultra shader. Upgrade your computer or something.

**Comment by R-T-B** [comment]
As for why it's required, it's so we don't have to debug code paths on 4-5 different settings, as well as require texture pack artists to provide that many source textures.  It's for simplicity basically, on our end if not yours.  Maintaining this thing is a huge effort as is.

My advice if you cannot update your computer is just to stick with the 1.8 release.  It has most of the features sans the latest graphics, anyways.  Closing as wontfix, sorry I can't do more but I'm only human.  We appreciate your understanding here.
