### ISSUE TITLE
Bump to 1.10?

### ISSUE THREAD

**Issue by cryptiklemur** [prestja/Kopernicus#23]
Would love to help with reporting any possible issues that show up in 1.10, but its currently locked at 1.9.1

**Comment by democat3457** [comment]
https://github.com/R-T-B/Kopernicus

**Comment by R-T-B** [comment]
As posted above, that's the bleeding edge branch where we support things like that.  It's actually pretty decent in it's 1.10 support, more than enough to enjoy a game with most packs.

1.10 is not planned to reach stable though, as in here.  We plan on waiting for 1.10's first patch.  Thanks for understanding, and feel free to try the other branch in the meantime.
