### ISSUE TITLE
Solar panels still generate too much power in some instances:

### ISSUE THREAD

**Issue by R-T-B** [prestja/Kopernicus#24]
As explained by OhioBob in his planet pack:

"Sorry to once again be the bearer of bad news, but I've found another issue with solar panels.  In all my previous tests, I positioned the probe between the Sun and Grannus so that the panels were illuminated by either one star or the other, but not both at the same time.  But I just noticed that when the probe is positioned so that panels receive light from both stars at the same time, the panels may generate more power than they should.  The screenshot below is an example in which the Sun and Grannus both lie in the same direction from the probe.  One panel is tracking the Sun and the other is tracking Grannus, but both are pointing the same direction as they should.  The one tracking Grannus has an energy flow of 1.708, which is about what it should be.  Even though the panel is tracking Grannus, the energy flow should be coming from the Sun since it's the nearest and most powerful light source.  The panel tracking the Sun has an energy flow of 57.005, which is way higher than it should be.  This is using the latest 1.9.1-6 build. "

Reference image:

https://i.imgur.com/XNXFLFH.jpg

Sadly, this indicates something is still up with how energy is calculated...  I'm not familiar with the code really, but I will be investigating this and producing test builds in my bleeding edge branch for now.  If anyone has any input, it would be most welcome.

**Comment by georgedorn** [comment]
I have the opposite problem; for many (all?) of the large retractable panels (e.g. OKEB-75R from Interstellar), if I load a save in which they are extended, they produce negative electricity.  After much fiddling, I've found I can work around this by retracting all panels, saving, and then loading the save; because [this section](https://github.com/prestja/Kopernicus/blob/master/src/Kopernicus/Components/KopernicusSolarPanels.cs#L108) is skipped for retracted panels.

**Comment by R-T-B** [comment]
Interesting, thanks for the good issue analysis!  This gives me an idea of where to start wheras before, I honestly had no idea.  I will see what can be done.  I believe these two seemingly seperate issues stem from a common source, as I know Ohiobob uses "test saves" with solar panels deployed.  Something happens to the math on the load of the save, I think.

**Comment by georgedorn** [comment]
I did a bunch more logging and couldn't figure out where things were going wrong.  I expected something in the `FixedUpdate()` method to be responsible, but after adding a ton of logging that all looks like it is behaving.

In fact, I could watch the log being written to, and everything was fine until after that function finished (they were even producing power) but then the panels moved to track whatever body and started producing negative power...

So I think it's something later, and maybe only specific panels?  It never seems to affect the non-retractable panels, or at least I haven't seen it.

I'm tempted to do a build with `KopernicusSolarPanels.cs` reverted to before that last panel fix branch, but I'm pretty sure I ran into the bug before updating to that.  Maybe it's something completely different, something about how 1.9.x interacts with NearFutureSolar in unexpected ways?

My logging attempt was here: https://github.com/georgedorn/Kopernicus/commit/efe2e54a60cb28728cf4c62f4da1cf5f1ed82b17

That got written to Kopernicus.Runtime.Log, and looks like:
```
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-bfs-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0
[LOG 18:46:13]:   totalFlow now:0
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0
[LOG 18:46:13]:   But scaling panel sunAOA to: 0
[LOG 18:46:13]:   Panel _flowRate:0
[LOG 18:46:13]:   Panel flowRate:0
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-bfs-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0
[LOG 18:46:13]:   totalFlow now:0
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0
[LOG 18:46:13]:   But scaling panel sunAOA to: 0
[LOG 18:46:13]:   Panel _flowRate:0
[LOG 18:46:13]:   Panel flowRate:0
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-bfs-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0.39965
[LOG 18:46:13]:   totalFlow now:984.789
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0.39965
[LOG 18:46:13]:   But scaling panel sunAOA to: 0.199825
[LOG 18:46:13]:   Panel _flowRate:13.1305200928661
[LOG 18:46:13]:   Panel flowRate:984.789
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-bfs-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0.787618
[LOG 18:46:13]:   totalFlow now:1940.793
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0.787618
[LOG 18:46:13]:   But scaling panel sunAOA to: 0.787618
[LOG 18:46:13]:   Panel _flowRate:25.8772395652916
[LOG 18:46:13]:   Panel flowRate:1940.793
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-copernicus-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0
[LOG 18:46:13]:   totalFlow now:0
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0
[LOG 18:46:13]:   But scaling panel sunAOA to: 0
[LOG 18:46:13]:   Panel _flowRate:0
[LOG 18:46:13]:   Panel flowRate:0
[LOG 18:46:13]: Running FixedUpdate for solar panel:nfs-panel-deploying-blanket-copernicus-1
[LOG 18:46:13]: Currently Tracking:SunLight
[LOG 18:46:13]: Starting bestFlux:1413.73991098932
[LOG 18:46:13]: Considering star:SunLight
[LOG 18:46:13]: Considering star:Valentine
[LOG 18:46:13]:   star is not trackingStar... (Valentine (Kopernicus.Components.KopernicusStar) vs SunLight (Kopernicus.Components.KopernicusStar))
[LOG 18:46:13]:   flux:0.000107230233988835
[LOG 18:46:13]:   vessel.solarFlux now:1413.73991497749
[LOG 18:46:13]:   totalFlux now:1413.73991497749
[LOG 18:46:13]:   totalAoA now:0
[LOG 18:46:13]:   totalFlow now:0
[LOG 18:46:13]: Finalizing Panel and Vessel stats
[LOG 18:46:13]:   Total Flux:2827.47982596681
[LOG 18:46:13]:   Panel sunAOA:0
[LOG 18:46:13]:   But scaling panel sunAOA to: 0
[LOG 18:46:13]:   Panel _flowRate:0
[LOG 18:46:13]:   Panel flowRate:0
```

**Comment by R-T-B** [comment]
Maybe it is limited to NearFutureSolar, I will ask my testers to try without that mod and see what happens.

I will be of limited use this next day or so, I have a family wedding coming up.  If anyone has input or PRs I will welcome them but there may be a delay until I can personally code, accept PRs, or otherwise address this.

I personally feel it has something to do with the load process, and maybe introducing a delay in when the power output calculation is activated on scene change may have the potential to work.  Unsure, but look at that angle maybe.

**Comment by R-T-B** [comment]
I think I solved this.

The issue is 

1.)  A lack of clamping on solar panel output, which makes every panel behave insanely efficiently/over spec (it's like over 9000 dude) at near orbit of stellar bodies because they have no ceiling on performance of ECs.

2.)  The loop needed to be restructured a bit in relation to calculating the ECs.  I had reasons for this, but I can't recall them for the life of me.  I just know that it works.  This was one of those "flash of brilliance" things I can't understand after the fact.  Maybe you can discern what I did.  It does seem to work now.

The commit is going to my bleeding edge for release testing.  You may view it here:

https://github.com/R-T-B/Kopernicus/commit/eca9590359552b7bdc82e2b901ce234eea67670c

**Comment by R-T-B** [comment]
Nevermind, that approach is not going to work.  It clamps EC to part spec, so Moho etc don't provide EC bonuses. 

I'll see what can be done, I have some other ideas.

**Comment by R-T-B** [comment]
I think overall, it's better to limit tracking to one star for now to limit bugs.  I've made some code that does this and it's not that bad:  Light (which affects EC) will only be taken in from the targeted/tracked star, heat/flux still affects entire vessel as intended.  The reason it is diffilcult to accept light from multiple sources is it requires a call to Lightshifter.applyphysics which does not appear to happen fast enough to update the values.  Hence, we get strange scenarios of stars taking on other stars properties for the EC calculations, leading to massive bugs.  I'm not sure this can be fixed honestly, it feels like a stock game limitation tied to the fact there can only be one solar intensity multiplier for the scene at any given time, and work arounds always seem to cause more harm than good.  Commentary welcome, but for now, I am testing the "tracked stars only" approach in my bleeding edge branch.  It's certainly less buggy, autotracking selection still works, etc.

See this commit:

https://github.com/R-T-B/Kopernicus/commit/b2d02bc6716bdbe2e98fcb08e61f5f27db5ab560

**Comment by R-T-B** [comment]
I'm working on a better method to calculate ECs from flux figures.  It might work, we'll see.  Leaving this open until we have a tested, working plan.

**Comment by R-T-B** [comment]
This is completely fixed now, so closing.  Feel free to reopen if you discover issues.
