### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by 0xd1cf001e** [prestja/Kopernicus#25]
The version in README.md is still 1.8.1. Please update it to 1.9.1 (and also the changelog)

**Comment by R-T-B** [comment]
Thanks for pointing this out.  We are aware and were waiting for CKAN status release to do this, but it wouldn't hurt to do some basic edits now.

**Comment by R-T-B** [comment]
I just updated the readme, so closing.  We'll put a more detailed changelog when we have it 100% stable.
