### ISSUE TITLE
CKAN Support.

### ISSUE THREAD

**Issue by R-T-B** [prestja/Kopernicus#29]
This is a catch all for CKAN support.  I think we are almost there, I've closed [nearly all ](https://github.com/prestja/Kopernicus/issues?q=is%3Aissue+is%3Aclosed)the 1.9.1 issues.  The only one remaining I'm grappling with is of course, Issue #26, but it's limited in scope and very situational.  Plus I have no idea where to fix it, so waiting on a fix would take a while.

That means once Issue #28 is closed, I think we can move ahead with CKAN.  Thoughts?  

When we do do CKAN BTW, I propose changing the logger line like I do with my bleeding edge builds, and starting the numbering over at 1.  This would be more in line with the conventional Kopernicus build process.  I could make a PR for that if you want, it should be prefixed with something like:

"Kopernicus CKAN Release " + Version

Rather than just "Kopernicus " + Version

PS:  To other team members:  I may be away from Discord for a bit due to having a lot more work and a lack of time.  So it's mostly up to @Prestja to manage this show from here for the week, I think.  It should be an easy decision though.  I'll update with status when I finally get Issue #28 closed, which will be my last for a week or so here.

**Comment by prestja** [comment]
Why is this necessary? Release candidates worthy of CKAN are just going to go on the primary Kopernicus repository.

**Comment by R-T-B** [comment]
> Why is this necessary? Release candidates worthy of CKAN are just going to go on the primary Kopernicus repository.

I just opened it for discussion of blocker issues (so we can prioritize them) given I'm going to be working at work a lot more where discord is blocked.  What part is unneccesary, you mean the versioning change?  That could be considered unneccesary, was just proposing it as an idea so the version count would not start high.  Seemed cleaner to me.  Maybe not.  That I don't care about either way, was just a proposal and irrelevant to the main issue, which is just to "get there."

Do you agree that Issue #26 can be skipped for now for CKAN release, but #28 must be dealt with?

**Comment by prestja** [comment]
Yes. I know #28 would be beyond irritating to me if I was an ordinary player.

**Comment by R-T-B** [comment]
Good, then #28 is my current goal.  We are on same page minus the versioning thing, which is your call anyways.  I'll let everyone know when that blocker issue is gone, then I say a few days wait and if nothing new crops up, we can CKAN it.

**Comment by R-T-B** [comment]
I think we fixed issue #28, but it has some nasty side effects.  I'm unable to get around to fixing them now because I am going through a system reinstall.

I should be back coding in earnest in 1-2 days.  Appologies for dropping a somewhat buggy potato build on the Bleeding Edge while doing it (it works, just not well past 1.9.  Comet issues maybe?)

**Comment by R-T-B** [comment]
I fixed the nasty side effect on issue #28.  I now have two more issues I consider blockers, Issue #30 and issue #31, which I will be working on in the bleeding edge, As of now, I consider them as the last remaining fixes before we consider CKAN.  I think if we get these two, CKAN could be considered pending a say, three day or so day wait period (to see if any new bugs).

**Comment by R-T-B** [comment]
Release candidate up, no bugs known other than the relatively minor Issue #26, so we are in a 2 day waiting period.  Please report any bugs you find, hopefully there are none to find!  If nothing major comes up CKAN is right around the corner.

**Comment by R-T-B** [comment]
Issue #32 is a CKAN blocker.  I am working on a fix now.

**Comment by R-T-B** [comment]
Issue #32 closed, we are in a 24 hour waiting period minimum again before we can consider CKAN.

**Comment by R-T-B** [comment]
Target for CKAN as of now, is Wednesday (tomorrow), and I consider us on track.

**Comment by R-T-B** [comment]
I plan one bugfix for the CKAN release, but overall it has done well.  I'm closing this issue, as such.
