### ISSUE TITLE
Inaccurate atmospheric temperature calculations

### ISSUE THREAD

**Issue by prestja** [prestja/Kopernicus#3]
https://forum.kerbalspaceprogram.com/index.php?/topic/194936-191-kopernicus-continued/&do=findComment&comment=3809504

**Comment by Keith-OHara** [comment]
The panelsFix2 branch at src/Kopernicus/Components/KopernicusStar.cs recomputes GetAtmoThermalStats for some reason, in the new code from commit 07230f34a7e44bc3c3b0f75b96e89424a0f339dd "CalculateFlux => CalculateFluxAt"

**Comment by R-T-B** [comment]
Good catch.  I'm sure that was done as part of the multistar support for solar panels, but atmospheres really don't need their thermal stats recomputed in this situation, do they?

EDIT:  That code would be broken in multistar situations anyways, as it only uses one "Sun" vector.  I recomend removing lines 283-291 from the present master of KopernicusStar, and testing.  They are commented under the heading "// Get Thermal Stats."  This should allow the stock game to calculate flux properly.

We will still only get atmospheric flux calculations from one star, but honestly, that's not a huge deal right now as long as it's the closest one, and it should be in most instances (isn't that what stock does?).  I hope I'm right anyways, Kopernicus is pretty foreign to me.


I'll look into it in detail tomorrow.  I don't recommend acting on this until I have had time to test.

EDIT EDIT:  At the end of a long night, I see no reason for that entire [07230f3 ](https://github.com/prestja/Kopernicus/commit/07230f34a7e44bc3c3b0f75b96e89424a0f339dd)commit.  I recommend removing it's changes, pending testing of course.

**Comment by R-T-B** [comment]
Don't revert that afterall, it's needed for multistar support.

I think I fixed it,  but I need a reliable way to test this issue.  Is there a test scenario I can setup easily for it?

**Comment by R-T-B** [comment]
Tested and fixed in PR #7

**Comment by R-T-B** [comment]
Or so I thought, it's still not right.  It appears to be applying temps to the vessel component and not the general atmosphere, as confirmed by AeroGUI.  Still working on this.

**Comment by Keith-OHara** [comment]
Shucks.  Must be something else in PanelsFix2.
The timeline could be confusing: this issue was actually opened a day before the merge (PanelsFix2 6022e3b5f1050be1287271adea6a8b8bbb47ccc6) that brought the into this branch.
Release 1.9.1-1 has the air temperature cold at the poles, warm at the equator, and 1.9.1-2 has uniform air temperature,

**Comment by R-T-B** [comment]
Unfortunately my proposed PR is not good enough.  EC is not functioning correctly at all.

I'm working on fixing that.  For now, do not merge.

**Comment by R-T-B** [comment]
This was fixed with last merge and will be included in next release, so closing.
