### ISSUE TITLE
Incorrect ScaledSpace atmospheric glow for multi-star systems

### ISSUE THREAD

**Issue by prestja** [prestja/Kopernicus#30]
https://forum.kerbalspaceprogram.com/index.php?/topic/194936-191-kopernicus-continued/&do=findComment&comment=3831455

https://forum.kerbalspaceprogram.com/index.php?/topic/194936-191-kopernicus-continued/&do=findComment&comment=3831479

**Comment by democat3457** [comment]
reee `rimColorRamp` is merely exposing the option "_rimColorRamp" in the builtin shaders "Terrain/Scaled Planet (RimAerial)" or "Terrain/Scaled Planet (RimAerial) Standard"

**Comment by OhioBob** [comment]
Further testing of this issue has uncovered that if the body uses an Eeloo template, the rim glow points to the correct star.  Of course one shouldn't be forced to use an Eeloo template, it should work with any template.  But perhaps Eeloo contains the solution to the problem.

**Comment by R-T-B** [comment]
I'm working on this in bleeding edge now.  I too think Eeloo is the key.

**Comment by R-T-B** [comment]
This is fixed on bleeding edge, awaiting testing for merge to stable.

**Comment by R-T-B** [comment]
Marking this as fixed, as it is in latest release.
