### ISSUE TITLE
Landing Gear Clipping Through Terrain, Vessel Slides Across Surface, Wheels do not work

### ISSUE THREAD

**Issue by sacr3dbac0n0** [prestja/Kopernicus#34]
Issue is indiscriminate and affects many planetary bodies from different planet packs by different authors. Vessel slides on the slightest slope and is not an issue with the brakes. The motors on wheels run, but the vessel does not move nor steer from it. It happens on all stock/modded gear and wheels. I have found no ways to alleviate this, new save, fresh reinstall, stripped down gamedata to Kopernicus and planet packs only to no effect. I am on Win x64 and currently on 1.9.1-7. It happens on both 1.8.1-1 and 1.10.1 bleeding edge I can confirm.

Let me know If you need any more information, I can easily reproduce this 100% of the time.

A video of a more extreme scenario: https://www.youtube.com/watch?v=KOVDijVEDf8&feature=youtu.be

![unknown](https://user-images.githubusercontent.com/69779657/95002609-d6110f00-058a-11eb-98b6-4557bae5acc1.png)

**Comment by R-T-B** [comment]
As this repo is basically dead, I'll close this and track this issue on the main Kopernicus/Kopernicus repo.  Thanks for the report!
