### ISSUE TITLE
Failure to load planets 

### ISSUE THREAD

**Issue by VabienArt** [prestja/Kopernicus#4]
Planets fail to load on some packs, including the Event Horizon, and Light Levels mods. Looking through the log, it seems to be trying to pull up a material which unity doesn't like, but I can't confirm that. 

[Log Here](https://drive.google.com/drive/folders/1min18oUtluegOFH5IVNWBf2HAckhf2v5?usp=sharing)

**Comment by prestja** [comment]
Issue seems to be with loading a material on body "Izetta"

**Comment by R-T-B** [comment]
Can you retry this with a newer release?  I don't know that it'll fix it, but it would establish if this issue is still there.

**Comment by VabienArt** [comment]
Issue Solved: Failure on pack side. Attempted to use built in textures that changed in 1.9.
