### ISSUE TITLE
1.10 Support

### ISSUE THREAD

**Issue by R-T-B** [prestja/Kopernicus#8]
I don't want to rush into anything, but given 1.10 is basically a parts pack, it may be possible to target it with a simple recompile.  I'm going to make some debug builds but need to test obviously.  Obviously the focus is 1.9 but if 1.10 is easy enough, we may as well begin targeting it.  I'll update with results.

**Comment by Poodmund** [comment]
Are you joking? 🤣  They've added in a completely new rendering system for Gas Giants?

https://forum.kerbalspaceprogram.com/index.php?/topic/195178-modders-notes-1100/

**Comment by R-T-B** [comment]
I'm aware (sorry if my "parts pack" comment was misleading, it's just what I see it as personally being it's biggest trait).  I see no reason we should not be able to clone it's effects, and in the meantime builds can still implement the planets the old way without the new shaders.  It's better than no support.

I'm not joking.  I opened this as a long term goal, not an immediate target, but it's worth investigating going forward.

**Comment by R-T-B** [comment]
The Jool swirls are as I suspected, only shader based.  They work fine in a 1.10 recompile of Koperncius.

Just updating on that front:

JNSQ also loads fine.  If you are interested in testing, please contact me.  We still likely have a lot of bugs to find.
![screenshot5](https://user-images.githubusercontent.com/2155778/86402864-6d4f8900-bc61-11ea-9303-81528992e0e1.png)

**Comment by R-T-B** [comment]
It seems unfortunately, I was a little eager there, lol.

The Jool shaders apply to all new templated gas giants.  Either we need to NOT template Jool to create a gas giant (not sure we can even do that), or we need some workaround code.  Every gas giant looks Joolish right now.

**Comment by R-T-B** [comment]
1.10 support is being worked on in my personal branch, [dev110](https://github.com/R-T-B/Kopernicus/tree/dev110)

I currently have it in basic feature parity with 1.9, but no control over the gas giant shaders.  Jool has them, every other templated planet at the moment has them manually shut off for compatability reasons (otherwise every gas giant looks like Jool).  We'll need to think of how to handle the new shader system going forward.

Feel free to use my work in the main repo when that time comes, of course.

**Comment by R-T-B** [comment]
dev110 is now basically in parity with release 1.9.1 builds feature wise.  All it's missing is an interface to the new gas giant shaders (templated bodies just switch them off now), but i am working on that in the background.  Obviously we will probably need to update config-parser for that as well.

Would you mind if I released some dev110 branch builds to the forums for beta testing alongside the other builds?  I feel a wider audience could find more bugs, particularly with the newly reimplemented particle system PR.

**Comment by R-T-B** [comment]
I am closing this as my bleeding edge branch has supported 1.10 for some time, and we have decided official will not target Kopernicus 1.10, but rather wait for the patch.

http://github.com/R-T-B/Kopernicus/
